#!/usr/bin/env bash
# FullPageOS generation script
# Helper script that runs in a Raspbian/others chroot to create the FullPageOS distro
# Written by Guy Sheffer <guysoft at gmail dot com>
# GPL V3
########
set -x
set -e

source /common.sh

unpack /filesystem/home/pi /home/pi pi
unpack /filesystem/boot /boot
unpack /filesystem/root_init /
unpack /filesystem/usr/share/plymouth /usr/share/plymouth

apt-get update

apt-get remove -y --purge scratch squeak-plugins-scratch squeak-vm wolfram-engine python-minecraftpi minecraft-pi sonic-pi oracle-java8-jdk bluej greenfoot libreoffice-common libreoffice-core freepats
apt-get autoremove -y

#apt-get tools
apt-get -y --force-yes install python2.7 git screen checkinstall avahi-daemon libavahi-compat-libdnssd1 xterm

if [ "$FULLPAGEOS_INCLUDE_CHROMIUM" == "yes" ]
then
    apt-get install -y --force-yes chromium-browser
    sudo -u pi sed -i 's@%BROWSER_START_SCRIPT%@/home/pi/scripts/start_chromium_browser@g' /home/pi/scripts/run_onepageos
fi

apt-get install -y --force-yes xdotool

#Install web stack
if [ "$FULLPAGEOS_INCLUDE_LIGHTTPD" == "yes" ]
then
    apt-get install -y lighttpd php-common php-cgi php
    lighty-enable-mod fastcgi-php
    #service lighttpd force-reload
    chown -R www-data:www-data /var/www/html
    chmod 775 /var/www/html
    usermod -a -G www-data pi
    systemctl enable clear_lighttpd_cache.service
    pushd /var/www/html
        #Put git clones in place
        if [ "$FULLPAGEOS_INCLUDE_DASHBOARD" == "yes" ]
        then
        gitclone FULLPAGEOS_DASHBOARD_REPO FullPageDashboard
            chown -R pi:pi FullPageDashboard
            chown -R www-data:www-data FullPageDashboard
            chmod 775 FullPageDashboard
            pushd FullPageDashboard
                sed -i "s@'INIT_URL_PATH', __DIR__ . '/init.txt'@'INIT_URL_PATH', '/boot/fullpagedashboard.txt'@g" config.php
            popd
        fi
        #Set Welcome screen
        if [ "$FULLPAGEOS_INCLUDE_WELCOME" == "yes" ]
        then
            gitclone FULLPAGEOS_WELCOME_REPO welcome
            chown -R www-data:www-data welcome
        fi
    popd

    echo "enabled" > /boot/check_for_httpd
else
    echo "disabled" > /boot/check_for_httpd
fi

#Install piControl
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
apt-get install -y nodejs insserv
npm install forever -g
cd /opt
git clone git://github.com/saturngod/piControl.git piControl
cp /opt/piControl/pictlnode /etc/init.d/pictlnode
chmod +x /etc/init.d/pictlnode
update-rc.d pictlnode defaults
insserv pictlnode


#override timezone
if [ "$FULLPAGEOS_OVERRIDE_TIMEZONE" != "default" ]
then
    echo "$FULLPAGEOS_OVERRIDE_TIMEZONE" > /etc/timezone
    dpkg-reconfigure -f noninteractive tzdata
fi

#override locale
if [ "$FULLPAGEOS_OVERRIDE_LOCALE" != "default" ]
then
    sed -i '/^#.* '"$FULLPAGEOS_OVERRIDE_LOCALE"' /s/^# //' /etc/locale.gen
    locale-gen
    update-locale LANG="$FULLPAGEOS_OVERRIDE_LOCALE"
fi

#override password
if [ "$FULLPAGEOS_OVERRIDE_PASSWORD" != "default" ]
then
    echo "pi:$FULLPAGEOS_OVERRIDE_PASSWORD" | chpasswd
fi

#echo "sudo -u pi startx /home/pi/scripts/run_onepageos &" >> /etc/rc.local
#echo "(sleep 15 ; sudo -u pi /home/pi/scripts/fullscreen) &" >> /etc/rc.local

#####################################################################
### setup services

echo "server time.nist.gov" >> /etc/ntp.conf
echo "server ntp.ubuntu.com" >> /etc/ntp.conf

rm -r /usr/sbin/policy-rc.d || true

#cleanup
apt-get clean
apt-get autoremove -y

#Add script to auto change the hostname in /etc/hostname
