#!/bin/bash
serial=$(cat /proc/cpuinfo | grep Serial | cut -d ' ' -f 2) && aehostdomain="https://battleaxes-api.ableengine.site/subscribe/"$serial
x11vnc -many -rfbauth /home/pi/.vnc/passwd &
while true
do
    if [ $(curl -sL -w "%{http_code}\\n" "$aehostdomain" -o /dev/null) == "200" ] || grep -q disabled "/boot/check_for_httpd" ; then
      (sleep 15 ; /home/pi/scripts/fullscreen) &
      xdotool mousemove 9000 9000
      /home/pi/scripts/start_chromium_browser
    fi
    sleep 1
done
