#!/bin/bash

# This script attempts a refresh, but only if the requested page returns successfully.
serial=$(cat /proc/cpuinfo | grep Serial | cut -d ' ' -f 2) && aehostdomain="https://battleaxes-api.ableengine.site/subscribe/"$serial

curl --fail "$aehostdomain" &> /dev/null
curlRetr="$?"

if [[ "$curlRetr" -ne "0" ]]; then
  echo "Waiting to refresh since server is having issues.";
  exit 1;
fi

echo "Refreshing page.";

export DISPLAY=:0
WID=$(xdotool search --onlyvisible --class chromium|head -1)
xdotool windowactivate ${WID}
xdotool key ctrl+F5

xdotool key F11
