#!/bin/bash

#serial=$(cat /proc/cpuinfo | grep Serial | cut -d ' ' -f 2) && aehostip=$(avahi-browse -d local _http._tcp --resolve -t | grep -A1 "Webpack Dev Server" | grep "hostname" | ping -q -c 1 -t 1 $(awk -F'[][]' '{print $2}') | grep PING | sed -e "s/).*//" | sed -e "s/.*(//") && nc -z $aehostip 3001 &> /dev/null; aepingtest=$? && if [[ $aepingtest = "0" ]]; then aehostdomain="http://$aehostip:3001?id="$serial; else aehostdomain="http://localhost/FullPageDashboard/battle.gif"; fi;

serial=$(cat /proc/cpuinfo | grep Serial | cut -d ' ' -f 2) && aehostdomain="https://battleaxes-api.ableengine.site/subscribe/"$serial

chromium-browser --kiosk --touch-events=enabled --disable-pinch --noerrdialogs --disable-session-crashed-bubble --app=$aehostdomain
